export const USER_STORY_REQUEST="USER_STORY_REQUEST";
export const USER_STORY_SUCCESS="USER_STORY_SUCCESS";
export const USER_STORY_FAILURE="USER_STORY_FAILURE";

export const USER_ACTIVE_STORY_REQUEST="USER_ACTIVE_STORY_REQUEST";
export const USER_ACTIVE_STORY_SUCCESS="USER_ACTIVE_STORY_SUCCESS";
export const USER_ACTIVE_STORY_FAILURE="USER_ACTIVE_STORY_FAILURE";

export const CREATE_STORY_REQUEST="CREATE_STORY_REQUEST";
export const CREATE_STORY_SUCCESS="CREATE_STORY_SUCCESS";
export const CREATE_STORY_FAILURE="CREATE_STORY_FAILURE";

export const FOLLOWERS_ACTIVE_STORY_REQUEST="FOLLOWERS_ACTIVE_STORY_REQUEST";
export const FOLLOWERS_ACTIVE_STORY_SUCCESS="FOLLOWERS_ACTIVE_STORY_SUCCESS";
export const FOLLOWERS_ACTIVE_STORY_FAILURE="FOLLOWERS_ACTIVE_STORY_FAILURE";

export const SET_STORIES_REQUEST="SET_STORIES_REQUEST";
export const SET_STORIES_SUCCESS="SET_STORIES_SUCCESS";
export const SET_STORIES_FAILURE="SET_STORIES_FAILURE";