export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAILURE="LOGIN_FAILURE";

export const REGISTER_REQUEST="REGISTER_REQUEST";
export const REGISTER_SUCCESS="REGISTER_SUCCESS";
export const REGISTER_FAILURE="REGISTER_FAILURE";

export const GET_PROFILE_REQUEST="GET_PROFILE_REQUEST";
export const GET_PROFILE_SUCCESS="GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAILURE="GET_PROFILE_FAILURE";

export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_FAILURE="UPDATE_PROFILE_FAILURE";

export const SEARCH_USER_REQUEST="SEARCH_USER_REQUEST";
export const SEARCH_USER_SUCCESS="SEARCH_USER_SUCCESS";
export const SEARCH_USER_FAILURE="SEARCH_USER_FAILURE";

export const USER_SUGESSION_REQUEST="USER_SUGGESION_REQUEST";
export const USER_SUGGESION_SUCCESS="USER_SUGGESION_SUCCESS";
export const USER_SUGGESION_FAILURE="USER_SUGGESION_FAILURE";

export const FOLLOW_USER_REQUEST= "FOLLOW_USER_REQUEST";
export const FOLLOW_USER_SUCCESS= "FOLLOW_USER_SUCCESS";
export const FOLLOW_USER_FAILURE= "FOLLOW_USER_FAILURE";

export const SEARCHED_USR_REQUEST="SEARCHED_USR_REQUEST";
export const SEARCHED_USR_SUCCESS="SEARCHED_USR_SUCCESS";
export const SEARCHED_USR_FAILURE="SEARCHED_USR_FAILURE";